### ISSUE TITLE
Publish on MATLAB FEX

### ISSUE THREAD

**Issue by scottclowe** [MOxUnit/MOxUnit#9]
I think the majority of MATLAB users who look for new packages look solely on [MATLAB FileExchange](http://mathworks.com/matlabcentral/fileexchange).

Adding MOxUnit there will garner a lot more traffic - especially if you add the [MATLAB xUnit Test Framework](http://uk.mathworks.com/matlabcentral/fileexchange/22846-matlab-xunit-test-framework) to the acknowledgements. Be sure to emphasise that the compatibility with Octave makes running tests on a CI server much easier - this is why I am using MOxUnit.

You can add a GitHub repo and (I believe) it will then only need to be added once - the content automatically tracks the repository.

**Comment by nno** [comment]
Thanks for the suggestion; I added a link:

http://it.mathworks.com/matlabcentral/fileexchange/54371-moxunit

Note that I did not link to the github repository because it seems that the Mathworks actually make a copy, which could make it subject to its Terms of Service (http://it.mathworks.com/matlabcentral/termsofuse.html). That does not seem desirable, as clause 2(a)iii makes software hosted on File Exchange non-free software through the "Content submitted to File Exchange may only be used with MathWorks products." clause

**Comment by scottclowe** [comment]
They have that as a clause?! I did not know that.

On 7 December 2015 at 14:31, Nikolaas N. Oosterhof <notifications@github.com
